/* 
EXAMPLES
ADD CONSTRAINT IN REFEREEE TABLE CALLED REFEREE NATIONALITY = "RefNat"
*/

CREATE TABLE Referee /* Referee and it's attributes */
(
	Ref_ID               INTEGER NOT NULL ,
	RefName              VARCHAR2(74) NOT NULL ,
	RefPhone             INTEGER NOT NULL ,
	RefAddress           VARCHAR2(74) NOT NULL ,
  RefNat               VARCHAR2(74) NOT NULL , /* THIS IS MY NEW ATTRIBUTE */
CONSTRAINT  XPKReferee PRIMARY KEY (Ref_ID)
);

/* Referee Table Info. = RefNat = 'Spanish' */    
INSERT INTO REFEREE (REF_ID,REFNAME, REFPHONE,REFADDRESS,REFNAT)VALUES(701,'Tim Howard',086283123,'18 Mersey Way','Spanish');
INSERT INTO REFEREE (REF_ID,REFNAME, REFPHONE,REFADDRESS,REFNAT)VALUES(702,'Darren Enfield',0851297746,'132 Greater Manchester Drive','Spanish');
INSERT INTO REFEREE (REF_ID,REFNAME, REFPHONE,REFADDRESS,REFNAT)VALUES(703,'Mark Clatenberg',0891156776,'85 Moore Street London','Spanish');
INSERT INTO REFEREE (REF_ID,REFNAME, REFPHONE,REFADDRESS,REFNAT)VALUES(704,'Larry Wilson',0833009978,'100 Benson Stree Lower Birmingham','Spanish');
INSERT INTO REFEREE (REF_ID,REFNAME, REFPHONE,REFADDRESS,REFNAT)VALUES(705,'Morgan Pederson',0871606123,'85 Bootham Terrace','Spanish');

/* USE THIS TO DISPLAY THE REFREE TABLE (RefNat) AND A NATURAL JOIN WITH THE CLUB */
SELECT *FROM Club NATURAL JOIN Referee;
